image: registry-vpc.cn-zhangjiakou.aliyuncs.com/vinkdong/tinyci:docker-19

stages:
  - build-app1
  - build-app2

build-app1:
  stage: build-app1
  script: 
    - cd app1
    - export SUB_APP_NAME=app1
    - docker_build
    - chart_build
  only:
    changes:
      - app1/**/*

build-app2:
  stage: build-app2
  script: 
    - cd app2
    - export SUB_APP_NAME=app2
    - docker_build
    - chart_build
  only:
    changes:
      - app2/**/*

.auto_devops: &auto_devops |
  curl -o .auto_devops.sh \
      "${CHOERODON_URL}/devops/ci?token=${Token}"
  if [ $? -ne 0 ];then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

  function docker_build(){
    docker build --build-arg commit=${CI_COMMIT_TAG} -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}-${SUB_APP_NAME} .
    docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}-${SUB_APP_NAME}
  }

  function chart_build(){
      CHART_PATH=`find . -maxdepth 3 -name Chart.yaml`
      helm package ${CHART_PATH%/*} --version ${CI_COMMIT_TAG}-${SUB_APP_NAME} --app-version ${CI_COMMIT_TAG}-${SUB_APP_NAME}
      echo "ok";
      
      
      # 通过Choerodon API上传chart包
      curl -X POST \
          -F "token=${Token}" \
          -F "version=${CI_COMMIT_TAG}-${SUB_APP_NAME}" \
          -F "file=@${PROJECT_NAME}-${CI_COMMIT_TAG}-${SUB_APP_NAME}.tgz" \
          -F "commit=${CI_COMMIT_SHA}" \
          -F "image=${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}-${SUB_APP_NAME}" \
          "${CHOERODON_URL}/devops/ci"
      # 判断本次上传是否出错
      if [ $? -ne 0 ]; then
          echo "upload chart error"
          exit 1
      fi
  }

before_script:
  - *auto_devops